# Generated by Django 5.2.15 on 2026-06-06 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=400, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('precision', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
                ('crawl_delay_seconds', models.PositiveSmallIntegerField(default=2)),
                ('notes', models.TextField(blank=True)),
                ('last_audited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('ph', 'PH'), ('duplex', 'Dúplex'), ('apartment', 'Departamento'), ('country_house', 'Quinta'), ('land', 'Terreno'), ('other', 'Otro')], default='other', max_length=30)),
                ('operation', models.CharField(default='sale', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('normalized_address', models.CharField(blank=True, db_index=True, max_length=300)),
                ('locality', models.CharField(blank=True, db_index=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, db_index=True, max_length=120)),
                ('currency', models.CharField(blank=True, db_index=True, max_length=8)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=16, null=True)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('garages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('covered_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('removed', 'Retirada')], db_index=True, default='active', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['currency', 'price'], name='properties__currenc_c47767_idx'), models.Index(fields=['property_type', 'status'], name='properties__propert_487234_idx'), models.Index(fields=['locality', 'neighborhood'], name='properties__localit_640c3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('precision', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=60)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='properties.property')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('precision', models.CharField(choices=[('exact', 'Exacta'), ('intersection', 'Intersección'), ('street', 'Calle'), ('neighborhood', 'Barrio'), ('manual', 'Confirmada manualmente')], max_length=20)),
                ('query', models.CharField(blank=True, max_length=400)),
                ('provider', models.CharField(default='source', max_length=60)),
                ('confidence', models.FloatField(default=0)),
                ('manually_corrected', models.BooleanField(default=False)),
                ('outside_target', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En curso'), ('success', 'Correcta'), ('partial', 'Parcial'), ('failed', 'Fallida')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('discovered', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='properties.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=800)),
                ('source_status', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('missing_runs', models.PositiveSmallIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='properties.agency')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.source')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.listing')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'url'), name='unique_listing_image')],
            },
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='properties.listing')),
            ],
            options={
                'ordering': ['-observed_at'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'content_hash'), name='unique_listing_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_listing'),
        ),
    ]
