# Generated by Django 5.2.15 on 2026-06-07 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En curso'), ('success', 'Correcta'), ('partial', 'Parcial'), ('failed', 'Fallida'), ('cancelled', 'Cancelada'), ('interrupted', 'Interrumpida')], db_index=True, default='pending', max_length=20)),
                ('selected_sources', models.JSONField(default=list)),
                ('worker_config', models.JSONField(default=dict)),
                ('max_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('max_listings', models.PositiveIntegerField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('discovering', 'Descubriendo'), ('running', 'En curso'), ('success', 'Correcta'), ('partial', 'Parcial'), ('failed', 'Fallida'), ('cancelled', 'Cancelada'), ('interrupted', 'Interrumpida')], db_index=True, default='pending', max_length=20)),
                ('workers', models.PositiveIntegerField(default=1)),
                ('total_discovered', models.PositiveIntegerField(default=0)),
                ('total_to_process', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('current_url', models.URLField(blank=True, max_length=1000)),
                ('logs', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='properties.scrapejob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_sources', to='properties.source')),
            ],
            options={
                'ordering': ['job_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('job', 'slug'), name='unique_job_source')],
            },
        ),
    ]
