# Generated by Django 5.2.15 on 2026-06-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_scrapejob_scrapejobsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='runner',
            field=models.CharField(choices=[('web', 'Web'), ('command', 'Consola')], default='web', max_length=16),
        ),
    ]
