# Generated by Django 5.2.15 on 2026-06-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_scrapejob_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='max_errors_per_source',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='request_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='scrape_mode',
            field=models.CharField(choices=[('trial', 'Prueba'), ('complete', 'Completo')], default='complete', max_length=16),
        ),
    ]
