# Generated by Django 5.2.15 on 2026-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_scrapejob_max_errors_per_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='detected_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='detected_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='detected_locality',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='detected_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='detected_neighborhood',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='location_confidence',
            field=models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('unknown', 'Desconocida')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='location_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_source',
            field=models.CharField(choices=[('listing', 'Listado'), ('detail', 'Detalle'), ('description', 'Descripcion'), ('map', 'Mapa'), ('inferred', 'Inferida'), ('unknown', 'Desconocida')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='personal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['detected_locality', 'detected_neighborhood'], name='properties__detecte_159b77_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_hidden', 'is_favorite', 'reviewed_at'], name='properties__is_hidd_e35e5a_idx'),
        ),
    ]
