# Generated by Django 5.2.15 on 2026-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_zone_inference'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='data_manually_corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='manual_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
