# Generated by Django 5.2.15 on 2026-06-13 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_listing_identities(apps, schema_editor):
    Listing = apps.get_model('properties', 'Listing')
    ListingIdentity = apps.get_model('properties', 'ListingIdentity')
    db_alias = schema_editor.connection.alias
    rows = []
    for listing in Listing.objects.using(db_alias).all().iterator(chunk_size=500):
        rows.append(
            ListingIdentity(
                source_id=listing.source_id,
                external_id=listing.external_id,
                url=listing.url,
                first_seen_at=listing.first_seen_at,
                last_seen_at=listing.last_seen_at,
                last_seen_reason='migration',
            )
        )
        if len(rows) >= 500:
            ListingIdentity.objects.using(db_alias).bulk_create(
                rows,
                ignore_conflicts=True,
            )
            rows = []
    if rows:
        ListingIdentity.objects.using(db_alias).bulk_create(
            rows,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_property_location_intelligence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True, max_length=800)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_reason', models.CharField(blank=True, max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_identities', to='properties.source')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source', 'last_seen_at'], name='props_ident_src_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_listing_identity')],
            },
        ),
        migrations.RunPython(seed_listing_identities, migrations.RunPython.noop),
    ]
