# Generated by Django 5.2.15 on 2026-06-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_dashboard_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='inferred_locality',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='inferred_partido',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='inferred_zone',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='territory_confidence',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='territory_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='territory_inferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='territory_needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='territory_source_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='propertylocationintelligence',
            name='locality_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertylocationintelligence',
            name='partido_name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['inferred_locality', 'inferred_zone'], name='prop_inferred_loc_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylocationintelligence',
            index=models.Index(fields=['partido_name', 'locality_name', 'zone_name'], name='locintel_territory_idx'),
        ),
    ]
