# Generated by Django 5.2.15 on 2026-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_property_inferred_locality_property_inferred_partido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejobsource',
            name='discovery_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejobsource',
            name='discovery_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejobsource',
            name='geocoding_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejobsource',
            name='geocoding_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejobsource',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejobsource',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
